# Usa a mesma imagem base que você já usava
FROM mongo:8.0.15

# Copia o script do seu repositório para a pasta correta dentro da imagem
COPY init-mongo.sh /docker-entrypoint-initdb.d/init-mongo.sh

# Garante permissão de execução (boa prática)
RUN chmod +x /docker-entrypoint-initdb.d/init-mongo.sh